### ISSUE TITLE
SOCKS5 proxy support

### ISSUE THREAD

**Issue by evanfarrar** [cloudfoundry-incubator/credhub-cli#18]
Given that most installation instructions/manifests/tools for deployment BOSH with credhub will not allow access from the internet to the credhub API, it would be helpful to allow for a proxy to be supplied to credhub-cli. This is the default, so it seems odd if all users have to solve this connection problem in their own way.

The BOSH CLI accepts $BOSH_ALL_PROXY to support this. I suggest we take a different tack with credhub, an experience which we also would like to to PR into BOSH if they will allow it. We would make all commands respect the host, key, and ssh username and start a SOCKS5 proxy as a goroutine before any connections to the credhub API occur. The experience could be:
```
export CREDHUB_GW_HOST=`bbl jumpbox-address`
export CREDHUB_GW_PRIVATE_KEY=`bbl ssh-key`
export CREDHUB_GW_USER=jumpbox

credhub api 10.0.0.6:8844
credhub login -u admin -p `bbl credhub-password`
```

My team has already created the SOCKS5 proxy management code in Go twice (in bosh-deployment-resource and in BBL), we would be happy to PR this in to credhub-cli if you would accept it.

**Comment by drnic** [comment]
socks5 support was added to go1.9 https://github.com/golang/go/commit/36f55a8b6125c9ae951487a0ad074b5c991f7b92

It looks like `master` and `1.5.0` suggest you're using `go1.9.1` to build `credhub` distributions. 

Does this mean that `export https_proxy=socks5://localhost:9999` should "just work"? (it didn't for me)

Is there some form of SOCKS5 proxy that does currently work?
