### ISSUE TITLE
User groups for credhub cli

### ISSUE THREAD

**Issue by gdenn** [cloudfoundry-incubator/credhub-cli#19]
# Feature Request
## Problem
We access the same credhub with multiple users through the credhub cli. But i don't want everyone to see all the variables in the credhub. E.g. we have credentials only relevant for specific Concourse Pipelines, credentials needed by an Administrator for our bosh deployment or simple credentials that help apps to access their dashboard.

As we are redeploying our bosh from time to time to include new features, it is important to us that the different people can access their passwords without conducting a system administrator.
But on the other hand we don't want to expose all credentials to everyone.

## Solution
credhub cli could support different user groups. Each group gets e.g. access to a certain set of credentials that match a prefix. For our Concourse users this prefix would be `/concourse`.

With the different user groups i could create user accounts with only the access permissions i am comfortable to give.

best

**Comment by danjahner** [comment]
This issue was moved to cloudfoundry-incubator/credhub#20

**Comment by danjahner** [comment]
Hi @gdenn - 

I've moved this issue to the main CredHub repo because the feature requested is part of the access control list functionality that we are working on in the server, not specifically a function of the CLI.

**Comment by gdenn** [comment]
@danjahner , ok thank you.
