### ISSUE TITLE
insecure flag for credhub login

### ISSUE THREAD

**Issue by gdenn** [cloudfoundry-incubator/credhub-cli#20]
# Feature Request
## Problem
We deployed credhub using a certificate that is not signed by a TA. Every time we want to login, we need to do `credhub login -u admin -p password --skip-tls-validation`. 
Since we got the cert we would rather than like to do so `credhub login -u admin -p password --ca-cert=some-cert --insecure`

If we try to authenticate against credhub cli with out cert (not TA signed), we receive the message "...your cert is not signed by a TA..."

## Solution
Add --insecure flag to `credhub login` to allow authentication through not TA signed certs.

**Comment by danjahner** [comment]
Hi @gdenn - 

Using the `--ca-cert` flag should be sufficient to authenticate with your server, without the need to also specifying `--skip-tls-validation`. Connection trust is validated for both CredHub and UAA, so if you have separate CAs for each, you need to specify both (with a stacked file or two `--ca-cert` flags). You should also double-check the cert details to ensure that it validates host names appropriately.

**Comment by crawsible** [comment]
@gdenn Can you try providing both the UAA CA and CredHub CA with successive `--ca-cert` values and close the issue if you're able to connect without `--skip-tls-validation`?

**Comment by gdenn** [comment]
@crawsible i am sry for the late response. I could manage to login with the procedure you described.

Thank you for the help.
