### ISSUE TITLE
Credhub --version hangs when unable to communicate with the server

### ISSUE THREAD

**Issue by jhvhs** [cloudfoundry-incubator/credhub-cli#27]
Sometimes it is necessary to determine the local CLI version before connecting to the server.
Feature proposal: `credhub --version` currently waits for the backend connection before reporting the CLI version. It would be better if the local version would be displayed instantly regardless of the ability to connect to the API backend.

**Comment by crawsible** [comment]
@jhvhs This was addressed in 1.5.3. Can you give it a shot and close the issue if you feel your request has been addressed?

**Comment by crawsible** [comment]
Closed due to lack of response.
