### ISSUE TITLE
Unable to set a credential of type json with a array body

### ISSUE THREAD

**Issue by rkoster** [cloudfoundry-incubator/credhub-cli#30]
```
> credhub set -n /foo -t json --value '["foo","bar"]'
The request could not be fulfilled because the request path or body did not meet expectation. Please check the documentation for required formatting and retry your request.
```

**Comment by rkoster** [comment]
this works:
```
credhub set -n /foo -t json --value '{"array": ["foo","bar"]}'
id: 9a2e199d-72ca-4ba7-966f-a8adfa1c637a
name: /foo
type: json
value:
  array:
  - foo
  - bar
version_created_at: 2017-12-18T15:40:15Z
```

but would like an array as the value not a nested under a key.

**Comment by crawsible** [comment]
@rkoster I agree that the current behavior rejects a valid JSON entity. For context, what are you storing in that array?

**Comment by rkoster** [comment]
a list of ip adresses, I'm trying to figure out how far I can take using credhub for all envrionment specific stuff in a bosh deployment. So far it works really nice. Before credhub we would store these tings in git repo's but you would always have to provide a key for accessing github/gitlab. Also you would have to create the repo. Just setting some variables in credhub is a much nicer user experience.

**Comment by rkoster** [comment]
@crawsible does the above answer give enough context? checking because I saw the linked tracker story is still blocked.

**Comment by kukgini** [comment]
@crawsible I have same situation with @rkoster. Can I expect this feature is implmented in near future?

**Comment by crawsible** [comment]
Apologies for the radio silence @rkoster @kukgini. We do plan on making this change but it is admittedly very low priority for us. Happy to take a PR in the meantime.

**Comment by rogeruiz** [comment]
@crawsible my team and I are considering taking on the support for this if it's a relatively small feature to add. Though it seems like it's not a feature for the CLI but rather for CredHub itself to accept `array` types. Is that true? Or can we make this change at the CLI layer?

For anyone else looking at how we solved this, we documented our process here. https://cloud.gov/docs/ops/design/secrets/#credhub-variable-types

**Comment by crawsible** [comment]
@rogeruiz Awesome! I believe you are correct -- the server (incorrectly) refuses JSON arrays as invalid JSON. @chhhavi any observations or guidance you'd like to add?

**Comment by LinuxBozo** [comment]
@crawsible @chhhavi PRs are now in for your review.

**Comment by crawsible** [comment]
@LinuxBozo Apologies; been a lot of vacation/illness the past few weeks. I'll prioritize this for review.
