### ISSUE TITLE
Password prompt should not show password in the clear

### ISSUE THREAD

**Issue by iredelmeier** [cloudfoundry-incubator/credhub-cli#33]
When providing a password for the `password` or `user` types via stdin, it seems like the password should be hidden the way that it is for other password prompts.

**Comment by mdelillo** [comment]
We implemented this [here](https://github.com/cloudfoundry-incubator/credhub-cli/commit/1c5b5bcd4bbec29c2c032746402747dfc2a8110b), it is in the [1.7.7 release](https://github.com/cloudfoundry-incubator/credhub-cli/releases/tag/1.7.7).
