### ISSUE TITLE
Prioritize environment variables over current config

### ISSUE THREAD

**Issue by tylerphelan** [cloudfoundry-incubator/credhub-cli#34]
What version of the credhub server you are using?
1.6.5

What version of the credhub cli you are using?
1.6.0

If you were attempting to accomplish a task, what was it you were attempting to do?

I'm hoping that when I switch my credhub environment variables from one credhub server to another server my credhub config will be configured without having to run `credhub api`.

Steps to reproduce:
```
$ export CREDHUB_CLIENT=...
$ export CREDHUB_SECRET=...
$ export CREDHUB_SERVER=server1
$ export CREDHUB_CA_CERT=cert1
$ credhub get -n /some/ref
> id: 1b34c341... (success)
...
$ export CREDHUB_CLIENT=...
$ export CREDHUB_SECRET=...
$ export CREDHUB_SERVER=server2
$ export CREDHUB_CA_CERT=cert2
credhub get -n /some/ref
> Post https://server1:8443/oauth/token: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

Potentially useful line number?:
https://github.com/cloudfoundry-incubator/credhub-cli/blob/be697aff6ba98c2f37dad63887ba1349dbd0d40c/commands/helpers.go#L57

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by crawsible** [comment]
I agree that the better behavior would be for the CLI to prioritize the env vars over its cached server info. We'll prioritize this change.

**Comment by benmoss** [comment]
I'd be in favor of removing the cached server functionality all together and just use environment variables and explicit flags for everything. It's too confusing to have two sources of configuration.

**Comment by mdelillo** [comment]
Given that removing the cached server functionality would break backwards-compatibility, we'll go ahead and prioritize the env vars if they are set.

**Comment by elenorebastian** [comment]
This looks like the current behavior!
