### ISSUE TITLE
When credhub is unreachable, credhub login/api and credhub find return confusing errors

### ISSUE THREAD

**Issue by ishustava** [cloudfoundry-incubator/credhub-cli#39]
### What version of the credhub server you are using?
N/A: This an issue only with the CLI.

### What version of the credhub cli you are using?
`v1.7.0`

### If you were attempting to accomplish a task, what was it you were attempting to do?
We were trying to verify that we can talk to credhub by running either of these commands:
```
credhub login
```
which returns:
```
Error connecting to the targeted API: "Get https://10.0.0.6:8844/info: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)". Please validate your target and retry your request.
```
OR 
```
credhub find
```
which returns:
```
Post https://10.0.0.6:8443/oauth/token: x509: certificate signed by unknown authority
```

### What did you expect to happen?
Because credhub was behind a firewall, I expected to see client timeout error when running `credhub find` instead of saying that the certificate is signed by unknown authority, which could be confusing. 

### What was the actual behavior?
```
Post https://10.0.0.6:8443/oauth/token: x509: certificate signed by unknown authority
```

### Steps to reproduce

Disallow traffic to credhub. For example, on AWS, remove the security group rule that allows client to reach credhub server on port 8844. 
Then run `credhub find` and `credhub login` and see that the error output is as described above.

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by edespino** [comment]
In my experience, I have seen a misleading message (`Post https://10.0.0.6:8443/oauth/token: x509: certificate signed by unknown authority`) when not logged into the BOSH CredHub (hosted on GCP) instance. After logging in, the error went away and I was able to access the service perperly.

Here is an example of my interaction:

```
08:52 $ credhub f
Post https://10.0.0.6:8443/oauth/token: x509: certificate signed by unknown authority
08:52 $ credhub l
Setting the target url: https://10.0.0.6:8844
Login Successful
08:53 $ credhub f

credentials: []
```

**Comment by dsabeti** [comment]
Yup, just had the same issue:
```
...
direnv: loading .envrc
Get https://10.0.0.6:8844/api/v1/data?current=true&name=bosh-bbl-env-winnipeg-2018-04-10t23-56z%2Fcf%2Fcf_admin_password: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "CredHub CA")

...
```

Eventually, we tried this:
```
$ credhub login
Setting the target url: https://10.0.0.6:8844
Login Successful
```

Then I could fetch my credentials as needed.
```
$ credhub get -n /bosh-bbl-env-winnipeg-2018-04-10t23-56z/cf/cf_admin_password
id: bf248854-bbfd-493b-8d4f-c2c1b2c55868
name: /bosh-bbl-env-winnipeg-2018-04-10t23-56z/cf/cf_admin_password
type: password
value: <REDACTED>
version_created_at: "2018-04-12T21:17:22Z"
```

Both the initial use of direnv and `credhub login` used the same variables, so I'm not sure why I had to log in again.

**Comment by martys34** [comment]
@ishustava This seems to be fixed in the latest version of the CLI. Can you confirm?

**Comment by ishustava** [comment]
Hey @martys34,

I'm not seeing this error anymore. I'm going to close this issue for now. Thanks!
