### ISSUE TITLE
Allow `--ca-cert` to accept the contents of the cert in addition to the path

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry-incubator/credhub-cli#4]
Noticed this story in flight: https://www.pivotaltracker.com/story/show/135819653

Seems like the command always expects a path to a cert file, while our team's workflow both locally and in CI is based around environment variables, e.g. `$CREDHUB_CA_CERT`. Could this flag be made to accept either a filepath or the contents of the file? I know Terraform uses a similar approach for many of its certs: https://github.com/hashicorp/terraform/blob/master/helper/pathorcontents/read.go.

Taking it a step further, additionally having the CLI recognize an environment variable directly, similar to `$CREDHUB_CLIENT`, would be even better.

**Comment by pivotal-danjahner** [comment]
Hey Lyle, 

It looks like two feature requests in this issue. 

* Accept CA content in addition to file references 
* Accept from env var in addition to flag for this value

I'll discuss what the former with the team to understand how that looks. The latter is easy to add.

**Comment by pivotal-danjahner** [comment]
Released in [1.3.0](https://github.com/cloudfoundry-incubator/credhub-cli/releases/tag/1.3.0)
