### ISSUE TITLE
credhub --version slow

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry-incubator/credhub-cli#46]
getting the version with `credhub --version` to get the current credhub cli version is slow.
because it wants to connect to credhub first.

**Comment by mdelillo** [comment]
@ramonskie thanks for reporting this! We are currently working on a feature that will significantly speed up the `--version` check because it will only reach out to the server once when logging in. You can track the progress of that story [here](https://www.pivotaltracker.com/story/show/160565578).
