### ISSUE TITLE
empty string is treated as a missing value

### ISSUE THREAD

**Issue by alex-slynko** [cloudfoundry-incubator/credhub-cli#5]
When I run this command 
`credhub login -u test -p '' -s https://10.2.1.252:8844`
I got request to enter password

It should be treated as a case when I send the wrong password.

**Comment by pivotal-danjahner** [comment]
Hey Alex - 

Thanks for the issue. I will mark this as a bug. 

I would classify this as low priority. There is not a use case for a password-less user so the negative scenario would be unlikely and only inconvenient. Let me know if you disagree. 

Thanks, 
Dan

**Comment by martys34** [comment]
@alex-slynko Is this still a feature you would like to see implemented? It's low priority for us and if the answer is no we will close this issue.

**Comment by alex-slynko** [comment]
Hey @martys34

We got initial error due to error in a bash script that skipped the error with bosh interpolate command and hang in CI.
One more issue was that CLI waited for input indefinitely.
 The issue is important for me, feel free to close it.

**Comment by dennisjbell** [comment]
Please reopen this - this is still present:

```
> credhub set -n '/my-bosh/my-deployment/cpi-config-property--project_id--3197c24b' -t 'value' -v ''
value: 
```
