### ISSUE TITLE
cannot rotate imported credential

### ISSUE THREAD

**Issue by fredwangwang** [cloudfoundry-incubator/credhub-cli#58]
What version of the credhub server you are using?
1.6.5

What version of the credhub cli you are using?
master branch

If you were attempting to accomplish a task, what was it you were attempting to do?
attempting to rotate the password that is imported to the credhub

What did you expect to happen?
expect to be able to rotate imported generated password

What was the actual behavior?
`The password could not be regenerated because the value was statically set. Only generated passwords may be regenerated.`

Process executed:
```bash
$ credhub generate -n testing -t password
$ credhub regenerate -n testing
$ credhub export > temp.yml
$ credhub delete  -n testing # simulating the behavior to migrate to another empty credhub instance
$ credhub import -f temp.yml
$ credhub regenerate -n testing 
The password could not be regenerated because the value was statically set. Only generated passwords may be regenerated.
```

Notes:
The same procees repeated with `-t cert`, we can regenerate successfully. At least this is an inconsistant experience

Proposed exported format if behavior for password regeneration stays the same:
```
credentials:
- name: /testing
  type: password
  value: kL2tf0qh26R2jfH9X3hKHw48fUnwBA
  generated: true
```

Please confirm where necessary:
* [ ] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

If you are a PCF customer with an Operation Manager (PCF Ops Manager) please direct your questions to support (https://support.pivotal.io/)

**Comment by kardolus** [comment]
This is expected behavior- credentials created with "credhub set" cannot be regenerated.
