### ISSUE TITLE
`credhub set -t value` defaults to string

### ISSUE THREAD

**Issue by mxplusb** [cloudfoundry-incubator/credhub-cli#64]
What version of the credhub server you are using?

```bash
λ credhub --version
CLI Version: 2.0.0
Server Version: 2.0.2
```

If you were attempting to accomplish a task, what was it you were attempting to do?

I was attempting to store a variable which determines how many instances of a BOSH deployment to deploy. With this credential storage:

```bash
λ credhub set -t value -n /bosh/rabbitmq/haproxy-instances -v 2
```

It should be storable as an int. When I deployed the BOSH release with `((haproxy-instances))` as the `/instance_groups/name=haproxy/instances` value, it failed because it's a string and not an integer.

What did you expect to happen?

The BOSH deployment to succeed because I passed a raw integer when creating the variable in credhub.

What was the actual behavior?

```bash
Task 28112

Task 28112 | 23:41:14 | Preparing deployment: Preparing deployment (00:00:01)
                     L Error: Property 'instances' value ("2") did not match the required type 'Integer'
Task 28112 | 23:41:15 | Error: Property 'instances' value ("2") did not match the required type 'Integer'

Task 28112 Started  Sun Nov 11 23:41:14 UTC 2018
Task 28112 Finished Sun Nov 11 23:41:15 UTC 2018
Task 28112 Duration 00:00:01
Task 28112 error

Updating deployment:
  Expected task '28112' to succeed but state is 'error'

Exit code 1
```

Please confirm where necessary:
* [ ] I have included a log output
* [x] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by ankeesler** [comment]
Hey @mxplusb - we have reproduced this issue locally. This is in line with the expected behavior per the [API docs](http://credhub-api.cfapps.io/version/2.1/#type-value20) as the value credential type only accepts strings.

We found, however, that if the credential type that you are interpolating into your BOSH manifest is JSON, then you can get an integer type to be substituted. For example, if you say `credhub set -t json -n /bosh/rabbitmq/haproxy-instances -v 2`, then that variable will be interpolated as an integer in the BOSH manifest. Would this be a valid workaround for your use case?

**Comment by ankeesler** [comment]
@crawsible @jparnala have y'all seen this type of request before where we are wanting to explicitly set values as integers in Credhub? Is this something that we have talked about supporting before?

**Comment by mxplusb** [comment]
> This is in line with the expected behavior per the API docs as the value credential type only accepts strings.

That's good to know. I think the CLI could use a significant overhaul on the documentation regarding `set`. The API docs are helpful if I was developing an API client, but I'm using the CLI and the docs don't cover use cases like this. The rest of the CF CLIs are very verbose in their help messages and don't point to external docs. I think that's definitely an area of improvement - the fact I had to file this issue to figure out how to store a different data type speaks to that.

> Would this be a valid workaround for your use case?

Yes, it should work just fine. Thanks! 👍

**Comment by ankeesler** [comment]
@mxplusb - thanks very much for your feedback, this is valuable for us to hear. Just to make sure we understand properly, is this docs shortcoming specifically in reference to the `set` CLI command, or is it an issue with all CLI commands?

Also, we could benefit from concrete examples of how the CLI could be improved - do you have any ideas off the top of your head? E.g., is it the fact that we are missing that value/password/json types are supposed to be strings?

**Comment by mxplusb** [comment]
Excellent question. I think the `--type` flag is useful, and I'd be interested in seeing it be extended/reassociated to support other types for static types that aren't part of a greater JSON structure. In my mind I could see something like this:

```bash
credhub set --type int -n /int_var -v 2
credhub set --type string-array -n /string_array_var -v '["a","b"]'
credhub set --type int-array -n /int_array_var -v '[1,2,3]'
credhub set --type bool-array -n /bool_array_var -v '[true,false]'
credhub set --type bool -n /bool_var -v 'true'
```

For the default `--type value`, it would be good to specify in the docs that `--type value` defaults to a `string` type so it's more clear.

How the Credhub API handles those specific flags internally I don't think matters to the end user so much, so you could really just have those be wrappers around the existing JSON implementation. That way you don't have a large logical overhead, but an operator then feels like they are storing the proper data type needed for a given consumer.

Thoughts?

**Comment by TisVictress** [comment]
@mxplusb  Thanks for your suggestions and feedback!

@jparnala Let's talk about this in our next sync up.

**Comment by jparnala** [comment]
We're taking your documentation feedback in mind for improvements. Closing this issue, thank you!
