### ISSUE TITLE
credhub-cli interpolate issues with concourse yml lookup rules

### ISSUE THREAD

**Issue by RedOnePrime** [cloudfoundry-incubator/credhub-cli#67]
What version of the credhub server you are using?
2.1.0

What version of the credhub cli you are using?
2.2.0

If you were attempting to accomplish a task, what was it you were attempting to do?
use the interpolate feature

What did you expect to happen?
it show me any missing key for the whole yml

What was the actual behavior?
It stops at the first key not found

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

The interpolate feature is rough to use when you are modifying pipelines for concourse integration. According to the current [lookup rules](https://docs.pivotal.io/p-concourse/4-x/credential-management.html) it will look at **/concourse/TEAM_NAME/PIPELINE_NAME/foo_param** and then **/concourse/TEAM_NAME/foo_param** to find your variable. Fair enough, that lets you have a clean yml with ((foo_param) as a variable format.

My team is utilizing this to be able to use common variables that the TEAM_NAME can share. However this seems in contrast with the current design of **credhub interpolate**. While you can tell credhub to add a prefix there is only an option for one, so you have choose between a prefix up to the PIPELINE_NAME or a prefix up to and including PIPELINE_NAME

Either way it will give you error that it can't find one variable set or another depending on your choice of prefix. This wouldn't be so bad if it would give output based on the whole file however that does not seem to be the case; it stops at the first error. Interestingly, in my case, the first two variables defined in my yml are one from each of those sets so I can't go further.

# Options:

1. I can interpolate fine if I edit my yml to be ((PIPELINE_NAME/foo_param) for variables specific to the pipeline and then prefix credhub interpolate with **/concourse/TEAM_NAME** but concourse doesn't like that, it won't find the variables starting with PIPELINE_NAME
2. Put all of my variables in PIPELINE_NAME scope. This lets me do ((foo_param) for everything and also interpolate. But that means I have to duplicate and maintain a heck of a lot of variables.
3. Edit yml to have all variables use the FQN so both concourse and credhub interpolate are happy. So you would have ((/concourse/TEAM_NAME/PIPELINE_NAME/foo_param)) and ((/concourse/TEAM_NAME/bar_param)) everywhere. This looks ugly/sloppy, but that aside our group is using TEAM_NAME to segregate values between environments. so foo_param needs to be different between different TEAM_NAMEs. I don't think there is a way to make TEAM_NAME dynamic (like fetch a credhub variable for it) so we don't want to hardcode it into the pipeline that needs to be used in different environments.

# Request:
So that being said, can we get multiple prefixes? Or can interpolate do a whole pass and output **all** not found keys instead of stopping at the first one? At least then I could spam the various prefixes and check the results. This might be problematic for larger files, though.

I know there was a lot of concourse stuff in here when this is credhub-cli. But you folks control direction on both. I am a little new to these tools so perhaps there is something I can't think of. But really it would be great to have better harmony between **credhub interpolate** and **concourse lookup rules**

Thanks.

-Red

**Comment by jtarchie** [comment]
Concourse has its own method for doing interpolation, this way it could have an interface for other vault-like systems. It does not use the `credhub-cli` interpolate functionality.

Why are you using `credhub-cli` with your concourse pipeline?

**Comment by martys34** [comment]
@RedOnePrime We have a PR open right now which would fix this issue: https://github.com/cloudfoundry-incubator/credhub-cli/pull/70

**Comment by ankeesler** [comment]
@RedOnePrime - the PR mentioned above (#70) was merged. Does this resolve any of your pain?

**Comment by jparnala** [comment]
@RedOnePrime Closing issue, please check PR submitted above. Thanks!
