### ISSUE TITLE
CLI can't parse response

### ISSUE THREAD

**Issue by taylorsilva** [cloudfoundry-incubator/credhub-cli#69]
**What version of the credhub server you are using?**
Server Version: 2.0.2

**What version of the credhub cli you are using?**
CLI Version: 2.2.0

**If you were attempting to accomplish a task, what was it you were attempting to do?**
Attempting to change the transitional flag from one version of a certificate to another.

**What did you expect to happen?**
The transitional flag to switch from the new certificate version to the older one AND for the cli to return a message along the lines of "Success!".

**What was the actual behavior?**
The transitional flag DID switch from the new to the old certificate, **BUT** the credhub-cli only displayed an error message. 
```
└─▪  credhub curl -d '{"version": "1024f501-f39a-43fb-8499-6ac9d704cb2b"}' -p /api/v1/certificates/d9a544ea-f1b3-49e3-8312-0872c2e277f6/update_transitional_version -X PUT
json: cannot unmarshal array into Go value of type map[string]interface {}
```
Because everything was successful server side, I'm assuming this is a client side only error in parsing the response. When I had the `-i` flag I can see that the response is `HTTP 200`.

```
└─▪ credhub curl -d '{"version": "1024f501-f39a-43fb-8499-6ac9d704cb2b"}' -p /api/v1/certificates/d9a544ea-f1b3-49e3-8312-0872c2e277f6/update_transitional_version -X PUT -i
HTTP/1.1 200
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Type: application/json;charset=UTF-8
Date: Tue, 08 Jan 2019 21:31:47 GMT
Expires: 0
Pragma: no-cache
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block

json: cannot unmarshal array into Go value of type map[string]interface {}
```
To reproduce follow this document: [https://github.com/pivotal-cf/credhub-release/blob/master/docs/ca-rotation.md](https://github.com/pivotal-cf/credhub-release/blob/master/docs/ca-rotation.md)
and instead of using curl use the credhub-cli for each command. You should get the error in the second step of step 2.

Please confirm where necessary:
* [x] I have included steps for reproduction
* [ ] My log includes an error message
* [ ] I have included a log output

**Comment by jparnala** [comment]
@taylorsilva Thank you for bringing this to our attention. We've fixed this and it will be available in our next release.
