### ISSUE TITLE
credhub cli errors with invalid character

### ISSUE THREAD

**Issue by marcus-sds** [cloudfoundry-incubator/credhub-cli#7]
When I try the credhub cli, it's failing with below message.
How can I debug this issue?
[ubuntu@ip-10-100-3-191 TEST bosh-test]$ credhub api --server=https://10.100.0.6:8443 --skip-tls-validation
invalid character '<' looking for beginning of value

**Comment by pivotal-danjahner** [comment]
Hello, 

It looks like you are targeting with the UAA port (8443), not the CredHub port (8844). It looks like the CLI is confused with the response that it is getting from that endpoint. 

I will put a story into the backlog to make the error message more clear, but updating the port should resolve your issue.
