### ISSUE TITLE
Feature request: add a visual browser for credhub

### ISSUE THREAD

**Issue by jtarchie** [cloudfoundry-incubator/credhub-cli#73]
# Problem

The `credhub` CLI includes a great way to explore the entire tree of creds via the command line.

Its difficulty comes when trying to get/set multiple fields. The `import` command was enabled to help alleviate this.

When it comes to exploring the data, `export` helped immensely. Being able to see all the values are transverse the tree is very useful. 

With any of these mechanisms, it can be repetitive to lookup fields, remember all the options to set, etc. Editing large YAML files can be difficult as it is YAML and remembering what’s on line 10 is hard when on line 1001.

# Proposal

The data for credhub is structured by types (ie password, username, etc) it fits well into the shape of a form. An HTML form would be useful to edit/add/delete values from credhub.

I’d like to propose `credhub-cli web` or maybe `credhub-cli explorer`.

When enabled from the local command line, it would start a local server, that only the current user can use (via the targeting creds on the machine), to explore their remote credhub.

Something similar to [vault ui](https://learn.hashicorp.com/vault/getting-started/ui).

## Features

* Tree explorer, which just allows you to expand/fold creds through the `path` of all the keys.
* Add, edit, or remove a specific key.

I’m happy to help work on this. I’d like to start a discussion to see if this a viable feature.

**Comment by ankeesler** [comment]
@jtarchie ah yes, the CredHub UI question. I would recommend one of two things.
- Check out this UI that another community member built: https://github.com/shreddedbacon/credhub-webui. The CredHub team does not support this, but you could reach out to the maintainer to chat with them about it.
- Talk to @jparnala. He has had a lot of good thoughts about where CredHub could go in the future, and where a UI fits into that future.

**Comment by jtarchie** [comment]
Sweet! Thanks for the follow up.

I'll close as there is a solution.
