### ISSUE TITLE
json format for export

### ISSUE THREAD

**Issue by squeedee** [cloudfoundry-incubator/credhub-cli#74]
What version of the credhub server you are using?
```
Server Version: 2.3.0
```
What version of the credhub cli you are using?
```
CLI Version: 2.4.0
```

If you were attempting to accomplish a task, what was it you were attempting to do?
export our creds to a secure backup using `credhub export`

What did you expect to happen?
To see a json formatted dump of the data (so that I can use `jq` to test the backup)

What was the actual behavior?
I got YAML... I'm fine with yaml, but in automated systems such as this, `jq` is an easier thing to depend upon than one of two flavors of `yq`

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [x] I have included steps for reproduction

**Comment by ankeesler** [comment]
@squeedee - this seems totally valid to me. Would you be willing to PR this change in?

**Comment by ankeesler** [comment]
@squeedee - two team members added this feature here: https://github.com/cloudfoundry-incubator/credhub-cli/commit/739c4cd7da30b8f8eb0173b01051cbec9ca0b2b2. Please try it out and let us know if it does not meet your needs!
