### ISSUE TITLE
interpolate is inconsistent with how it treats empty/valid files

### ISSUE THREAD

**Issue by kcboyle** [cloudfoundry-incubator/credhub-cli#75]
What version of the credhub server you are using?
unknown. Using credhub from concourse 5.1

What version of the credhub cli you are using?
2.4.0

If you were attempting to accomplish a task, what was it you were attempting to do?
We were attempting to interpolate an empty file, but got an error. When running another test with invalid yaml in that file, we did not get an error. 

What did you expect to happen?
I expected a consistent experience for credhub interpolate when using an empty file or invalid file

What was the actual behavior?
One returned an error, the other did not

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

if you had an empty file, credhub interpolate fails. However, if you gave that same file minimal yaml (`---`) with nothing else in it, it would pass. If you also give it a file with `-` or `invalid: ` as the only file contents, this also does not return an error.

```
→ credhub interpolate --file minimal-yaml.yml
null

→ echo $?
0

→ credhub interpolate --file invalid-yaml.yml
null

→ echo $?
0

→ credhub interpolate --file empty-yaml.yml
Error: empty-yaml.yml was an empty file

→ echo $?
1
```

**Comment by ankeesler** [comment]
Fixed in https://github.com/cloudfoundry-incubator/credhub-cli/releases/tag/2.5.0. Thanks!
