### ISSUE TITLE
credhub export/import loses 'signs' and 'signed_by' fields

### ISSUE THREAD

**Issue by KaiHofstetter** [cloudfoundry-incubator/credhub-cli#84]
What version of the credhub server you are using?
Server Version: 2.5.6

What version of the credhub cli you are using?
CLI Version: 2.6.2

If you were attempting to accomplish a task, what was it you were attempting to do?
Migrate certificates from one credhub server to another credhub server by using
```
$ credhub export > test-export
$ credhub import --file=test-export
```

What did you expect to happen?
Certificates with filled ``signs`` and ``signed_by`` fields:

CA:
```json
{
  "id": "ac06b2ea-3ac4-4f11-a6bd-f3ee7a5ef071",
  "name": "/dns_healthcheck_tls_ca",
  "signed_by": "/dns_healthcheck_tls_ca",
  "signs": [
     "/dns_healthcheck_server_tls",
     "/dns_healthcheck_client_tls"
  ],
}
```

Signed certificate:
```json
{
  "id": "5a1e0e4d-301e-41ac-92c8-c934ae9aec17",
  "name": "/dns_healthcheck_server_tls",
  "signed_by": "/dns_healthcheck_tls_ca",
  "signs": [],
}
```

What was the actual behavior?
The ``signs`` and ``signed_by`` fields were empty:

CA:
```json
{
  "id": "ac06b2ea-3ac4-4f11-a6bd-f3ee7a5ef071",
  "name": "/dns_healthcheck_tls_ca",
  "signed_by": "/dns_healthcheck_tls_ca",
  "signs": [],
}
```

Signed certificate:
```json
{
  "id": "5a1e0e4d-301e-41ac-92c8-c934ae9aec17",
  "name": "/dns_healthcheck_server_tls",
  "signed_by": "",
  "signs": [],
}
```

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [x] I have included steps for reproduction

If you are a PCF customer with an Operation Manager (PCF Ops Manager) please direct your questions to support (https://support.pivotal.io/)

**Comment by ankeesler** [comment]
@KaiHofstetter thank you for this submission. We have received this request before. The TL;DR is that the `export`/`import` CLI feature was contributed to the CLI via a community PR and thus is missing some features. It is expected behavior that the post-`import` in-API certificate forest would be missing the `signed_by` and `signs` information, because that information is never written out in the `export`.

Would you be amenable to submitting a PR for this behavior?

**Comment by ankeesler** [comment]
Also, can you tell me why you use this `export`/`import` command flow, as opposed to, say, `bbr`? We are doing some research on these two CLI commands.

**Comment by KaiHofstetter** [comment]
@ankeesler thank you for your feedback.
We are using {{export / import}} to migrate certificates/credentials between CredHub instances. It seemed to be the easiest way.
We were not aware of the fact that it does not include the {{signed_by}} and {{signs}} fields.

I'll look into it and provide a PR if it is feasible.

**Comment by KaiHofstetter** [comment]
@ankeesler I looked into to the issue.

The problem is that `credhub export` exports the `ca` value of a signed cert instead of the `ca_name` and `credhub import` only fills the `signed_by` and `signs` fields if the cert contains the `ca_name`:

```
- name: /cert
  type: certificate
  value:
    ca_name: /ca
    certificate: ...
    private_key: ...
```

I think there are two ways to fix it:
a) `credhub export` exports `ca_name` instead of the `ca` value for signed certs
or
b) `credhub import` tries to find in the import file the `ca_name` for used `ca` values

I would opt for option a) and provide a PR if that is ok.

**Comment by ankeesler** [comment]
@KaiHofstetter thank you for looking into this. We like option a) as well. Please do provide a PR. Thank you for your willingness to do this.

Two notes for your PR:
- When we have tried to do this in the past, we have run into snags with the ordering of `export`ed certificates. That is, on `import`, if a `ca_name` refers to a certificate that has not yet been hit in the `export`ed file, then we would not be able to use the `ca_name` in the request to the API. We would recommend that `import` contain logic to reorder these certificates in memory to ensure that this does not happen. Putting this logic in `import` also protects against a corner case where someone writes their own `export` file which does not necessarily have certificates in the right order.
- Please do write tests for this feature as well. Augmenting the current set of `import`/`export` tests would be a good path forward.

**Comment by KaiHofstetter** [comment]
@ankeesler I just added the feature to the `export` code. The `import` code already handles `ca_name` correctly and also ensures the correct import order of certificates and cas (see [here](https://github.com/cloudfoundry-incubator/credhub-cli/blob/0fffecb4557e8895963cf0f36b76b4e8e8ab8d4e/commands/import_test.go#L276-L326))

**Comment by LizClaireMorris** [comment]
@KaiHofstetter Thanks for the PR, we'll review it.
