### ISSUE TITLE
feature request: Credhub set with credhub generating secret on the fly

### ISSUE THREAD

**Issue by cwb124** [cloudfoundry-incubator/credhub-cli#90]
What version of the credhub server you are using?
2.5.11

What version of the credhub cli you are using?
2.6.2

If you were attempting to accomplish a task, what was it you were attempting to do?
Creating a credhub json entry with identity and password
`credhub set -t json /n /mypath/credential -v '{"identity":"CLIENT_NAME","password":"$PASSWORD"}'`

What did you expect to happen?
I would like/expect a way to have credhub generate the client password on the fly for me.

What was the actual behavior?
I have to generate a password in a previous step and then provide it to the credhub set command.

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [X ] I have included steps for reproduction

**Comment by jknostman3** [comment]
@cwb124 Thank you for reaching out. This is an interesting feature request and we are going to make note of it in our Tracker, however, this currently isn't a priority in our backlog with the other tracks of work we have going. I apologize that we won't be able to get to this in the near term but we do accept PRs as well.

**Comment by jknostman3** [comment]
Closing this issue for now. Given our current priorities, a fix isn't likely in the near term. We will reopen this issue when we can prioritize. Please let us know if we have any questions.
